export const uiPage = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Work Item Monitor</title><style>
:root{font:16px system-ui,sans-serif;color:#17202a;background:#f4f1eb}body{max-width:1100px;margin:0 auto;padding:24px}header{display:flex;justify-content:space-between;align-items:baseline;gap:16px}h1{font-size:1.8rem}a{color:#075985}.card{background:#fff;border:1px solid #d6d3d1;border-radius:8px;padding:16px;margin:12px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:12px}.muted{color:#57534e}.error{color:#991b1b}.badge{font-size:.8rem;padding:3px 7px;border-radius:999px;background:#e7e5e4}.mono{font-family:ui-monospace,monospace;white-space:pre-wrap;overflow:auto}button{font:inherit}@media(max-width:600px){body{padding:14px}header{display:block}}
</style></head><body><header><h1>Work Item Monitor</h1><span id="updated" class="muted"></span></header><main id="app">Loading...</main>
<script type="module">
const app=document.querySelector('#app'); const updated=document.querySelector('#updated');
const esc=(v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function load(){try{const detail=location.hash.match(/^#\/work-item\/(.+)$/);if(detail){const item=await fetch('/api/work-items/'+detail[1]).then(r=>{if(!r.ok)throw new Error('work item not found');return r.json()});app.innerHTML='<p><a href="#">Back to overview</a></p><article class="card"><h2>'+esc(item.title)+'</h2><p><span class="badge">'+esc(item.phase||item.workflowStatus||'unknown')+'</span> '+esc(item.taskId)+'</p><p class="mono">'+esc(item.context||'No task context available.')+'</p><h3>Execution history</h3><ol>'+item.history.map(e=>'<li><strong>'+esc(e.type)+'</strong> <span class="muted">'+esc(e.time||'')+'</span></li>').join('')+'</ol></article>';return}const overview=await fetch('/api/overview').then(r=>r.json()); updated.textContent='Updated '+new Date(overview.refreshedAt).toLocaleTimeString(); app.innerHTML=(overview.errors||[]).map(e=>'<p class="error">'+esc(e)+'</p>').join('')+'<div class="grid">'+overview.items.map(i=>'<article class="card"><a href="#/work-item/'+encodeURIComponent(i.taskId)+'"><strong>'+esc(i.title)+'</strong></a><p><span class="badge">'+esc(i.phase||i.workflowStatus||'unknown')+'</span> '+esc(i.taskState||'')+'</p><p class="muted">'+esc(i.taskId)+'</p>'+(i.failure?'<p class="error">'+esc(i.failure)+'</p>':'')+'</article>').join('')+'</div>'+(overview.items.length?'':'<p class="muted">No work-item executions found.</p>');}catch(e){app.innerHTML='<p class="error">Unable to load monitoring data: '+esc(e.message)+'</p>'}}
load();setInterval(load,5000);
</script></body></html>`;
